### ISSUE TITLE
when i transform model ,i got keyError: "torch.CudaTensor"

### ISSUE THREAD

**Issue by visonpon** [clcarwin/convert_torch_to_pytorch#13]
@clcarwin

**Comment by salihkaragoz** [comment]
@visonpon Hello, 

I also got the same error, did you overcome this problem?
If it is, how to solve? 
Can you explain?

Thanks in advance...

**Comment by Vandermode** [comment]
@salihkaragoz  I resolve this issue by 
```
net = torch.load('model.net')
net = net:float()
torch.save('model_cpu.net')
```
which transfers your model from gpu into cpu.

**Comment by dmortem** [comment]
@Vandermode 
Hi, when I try your codes, it shows 'SyntaxError' in "net:float()". How to transfer the model from gpu into cpu?
Here is my codes:
`import torch
net = torch.load('umich-stacked-hourglass.t7')
net = net:float()
torch.save('model_cpu')`
