### ISSUE TITLE
plan to support FaceNet or OpenFace?

### ISSUE THREAD

**Issue by thnkim** [clcarwin/convert_torch_to_pytorch#2]
Great utility!
Do you have a plan to support FaceNet or OpenFace also?
The models have nn.SpatialConvolutionMM and nn.Inception, which are not supported yet :(

Thank you!

**Comment by clcarwin** [comment]
nn.SpatialConvoltuionMM can drop in replacement for nn.SpatialConvoltion.
Modify the lines:
```if name == 'SpatialConvolution':```
to
```if name == 'SpatialConvolution' or name == 'SpatialConvolutionMM' :```

nn.Inception is not a torch standard layer. PyTorch can not load it, this script is hard to support it.
