### ISSUE TITLE
unknown type id 21810 3808.

### ISSUE THREAD

**Issue by herleeyandi** [clcarwin/convert_torch_to_pytorch#22]
Hello I run the script and get this error
`torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 218103808.`
here is link for the model [LINK](https://github.com/satoshiiizuka/siggraph2016_colorization/blob/master/download_model_imagenet.sh)

**Comment by clcarwin** [comment]
Package ```nngraph``` is not supported.

**Comment by xxAna** [comment]
@clcarwin Thank you for your sharing. And I wonder if there are any ways to convert a torch model in nngraph to pytorch?
