### ISSUE TITLE
It doesn't work with some models

### ISSUE THREAD

**Issue by salihkaragoz** [clcarwin/convert_torch_to_pytorch#34]
I didn't convert some specific models.

https://github.com/facebook/fb.resnet.torch/tree/master/pretrained
Resnet-18, Resnet-34, Resnet-50, ......, Resnet-200
AttributeError: type object 'torch.cuda.FloatStorage' has no attribute 'from_buffer'

https://github.com/umich-vl/pose-hg-demo
Stacked-Hourglass
KeyError: 'torch.CudaTensor'

How to overcome these issues?
Thanks in advance...

**Comment by LancherJOJO** [comment]
aaa

**Comment by dmortem** [comment]
Hi, I have the same problem when I convert hourglass model to pytorch version, how can I solve it? Thanks a lot!

**Comment by salihkaragoz** [comment]
Hi, As far as I remember I didn't succeed in converting the model. Because the hourglass model has some different layers(blocks) which are absent in torch.legacy. You can try directly the pytorch version of Hourglass. (https://github.com/bearpaw/pytorch-pose)
Have a look these issues to understand problem.
https://github.com/clcarwin/convert_torch_to_pytorch/issues/37 https://github.com/clcarwin/convert_torch_to_pytorch/issues/33 https://github.com/clcarwin/convert_torch_to_pytorch/issues/30 https://github.com/clcarwin/convert_torch_to_pytorch/issues/26
:wave:

**Comment by dmortem** [comment]
Thank you!

**Comment by vsoorya** [comment]
@dmortem Hi, did you succeed in converting the hour glass model to pytorch? If so, can you please share how you did it?
Thanks
