### ISSUE TITLE
Unsolvable error

### ISSUE THREAD

**Issue by shashankvkt** [clcarwin/convert_torch_to_pytorch#35]
Hi.. following your repository..I encountered the following error

    Traceback (most recent call last):
    File "convert_torch.py", line 314, in <module>
    torch_to_pytorch(args.model,args.output)
    File "convert_torch.py", line 303, in torch_to_pytorch
    lua_recursive_model(model,n)
    File "convert_torch.py", line 64, in lua_recursive_model
    copy_param(m,n)
    File "convert_torch.py", line 44, in copy_param
    if m.weight is not None: n.weight.data.copy_(m.weight)
    RuntimeError: The expanded size of the tensor (3) must match the existing size (27) at non-singleton dimension 3

I am trying to convert vgg_face.t7 into pytorch model. Could you kindly assist me to solve this error.
Any sort of assistance would be highly appreciated.
Thanks in advance

**Comment by omersumer** [comment]
I had the same error when I convert VGG-Face torch model to pytorch. It must be related to a Pytorch update (my Pytorch version is 0.5.0a0+7924530).
It says that tensor sizes (weights of Conv2d layers) are not matching. I changed line 44 like this:
```
if m.weight is not None: 
	m.weight.data = m.weight.view(n.weight.size())
	n.weight.data.copy_(m.weight)
```
I did not look through the rest of convert_torch.py file, but at least it works in Aamir Khan's picture :)

**Comment by lucygan** [comment]
@omersumer seems that this method solved the problem as @shashankvkt mentioned.

**Comment by luciagan** [comment]
I had the same error @shashankvkt , and answer from @omersumer perfectly solved my problem.  :)

**Comment by shashankvkt** [comment]
@omersumer  sorry for the late response. Thank you for your help. It worked.
